---
name: Publish Pages

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [src/**, package.json, .github/workflows/publish_pages.yaml]

jobs:
  Pages:
    runs-on: [ubuntu-24.04]

    permissions:
      contents: read # Required to checkout repository.
      id-token: write # Required to authenticate via OIDC.
      pages: write # Required to publish GitHub Pages.

    concurrency:
      group: github-pages
      cancel-in-progress: true

    environment:
      name: github-pages
      url: ${{ steps.publish.outputs.page_url }}

    env:
      NODE_ENV: production
      BASE_URL: /${{ github.event.repository.name }}/

    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          cache: npm
          node-version: 23

      - name: Cache Node modules
        id: cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          key: node-modules-${{ hashFiles('package-lock.json') }}
          path: node_modules

      - name: Install Node modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm clean-install

      - name: Build GitHub Pages
        run: npm run build

      - name: Upload GitHub Pages
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: dist/public/
          retention-days: 1

      - name: Publish GitHub Pages
        id: publish
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
        with:
          preview: true
